name: Compile Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qtcreator \
            qtbase5-dev \
            qt5-qmake \
            make \
            g++ \
            libgl1-mesa-dev \
            qtmultimedia5-dev \
            libqt5serialport5-dev \
            qttools5-dev-tools \
            qttools5-dev \
            libfftw3-dev \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi \
            libnewlib-arm-none-eabi

      - name: Prepare library directory
        run: |
          mkdir -p src/software/EMBO/lib/ubuntu_18
          ln -sf /usr/lib/x86_64-linux-gnu/libfftw3.a src/software/EMBO/lib/ubuntu_18/libfftw3.a

      - name: Compile PC Application
        run: |
          cd src/software/EMBO
          qmake EMBO.pro
          sudo make -j$(nproc)

      - name: Compile G431 Firmware
        run: |
          make -C src/firmware/board/STM32G431KB -j$(nproc)

      - name: Upload G431 Firmware Binary
        uses: actions/upload-artifact@v4
        with:
          name: EMBO_G431KB_Firmware
          path: |
            src/firmware/board/STM32G431KB/build/EMBO_G431KB.bin
            src/firmware/board/STM32G431KB/build/EMBO_G431KB.hex
            src/firmware/board/STM32G431KB/build/EMBO_G431KB.elf
